<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name=description
          content="GotMoney App - Gerenciador financeiro pessoal. Controle suas despesas online e sem custos!">
    <meta name=keywords
          content="finan&ccedil;as, despesas, or&ccedil;amento, gerenciador, controle, planejamento, financeiro, pessoal, familiar, contas">
    <meta name=author content="Mauricio Lauffer">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>GotMoney App - Gerenciador financeiro pessoal</title>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="512998861746.apps.googleusercontent.com">
    <link rel="stylesheet" href="./css/gotmoneyapp.min.css">
    <link rel=icon href="./images/favicon.ico" type="image/ico">
</head>
<body class="sapUiBody">
<div id="content"></div>
<script type="text/javascript" id="sap-ui-bootstrap"
        src="./js/resources/sap-ui-core.js" data-sap-ui-theme="sap_bluecrystal"
        data-sap-ui-libs="sap.m" data-sap-ui-bindingSyntax="complex"
        data-sap-ui-preload="async" data-sap-ui-compatVersion="edge"
        data-sap-ui-frameOptions="deny">
</script>
</body>
</html>